spring:
  application:
    name: zuul

zuul:
  routes:
    transaction-service: /service/**
    eureka: /discovery/**
  ignored-services: '*'

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: false
